// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_FpuLJQRPB4oSd9ToFD-eqE1JJ88Mkuc',
    appId: '1:891793719511:web:929c3fd324dc8bb87e7092',
    messagingSenderId: '891793719511',
    projectId: 'app-voluntariado-88af3',
    authDomain: 'app-voluntariado-88af3.firebaseapp.com',
    storageBucket: 'app-voluntariado-88af3.firebasestorage.app',
    measurementId: 'G-9NL7NDXKL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeHBR1K0F5QAn-63ADVsiME_PxCE5YsAk',
    appId: '1:891793719511:android:8b6ac2f5bb6192b57e7092',
    messagingSenderId: '891793719511',
    projectId: 'app-voluntariado-88af3',
    storageBucket: 'app-voluntariado-88af3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMeYTDUdmQsqpmeWuXRGF_CezQcqB8Gks',
    appId: '1:891793719511:ios:8bc2a08b0e0ad8e57e7092',
    messagingSenderId: '891793719511',
    projectId: 'app-voluntariado-88af3',
    storageBucket: 'app-voluntariado-88af3.firebasestorage.app',
    iosBundleId: 'com.example.frontendFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMeYTDUdmQsqpmeWuXRGF_CezQcqB8Gks',
    appId: '1:891793719511:ios:8bc2a08b0e0ad8e57e7092',
    messagingSenderId: '891793719511',
    projectId: 'app-voluntariado-88af3',
    storageBucket: 'app-voluntariado-88af3.firebasestorage.app',
    iosBundleId: 'com.example.frontendFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_FpuLJQRPB4oSd9ToFD-eqE1JJ88Mkuc',
    appId: '1:891793719511:web:8c26dd2d02f168e17e7092',
    messagingSenderId: '891793719511',
    projectId: 'app-voluntariado-88af3',
    authDomain: 'app-voluntariado-88af3.firebaseapp.com',
    storageBucket: 'app-voluntariado-88af3.firebasestorage.app',
    measurementId: 'G-VLQEC0J8MT',
  );
}
